server:
    port: 8080

spring:
    main:
      allow-bean-definition-overriding: true
    application:
        name: xingmu-user-service
    datasource:
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
      url: jdbc:shardingsphere:classpath:shardingsphere-user.yaml
    data:
      redis:
        host: localhost
        port: 6379
        database: 0


mybatis-plus:
  mapper-locations: classpath*:META-INF/mybatis/mapper/*.xml

bloom-filter:
  name: xingmu-user-bloom-filter
  expectedInsertions: 1000
  falseProbability: 0.01

xingmu:
  jwt:
    secret: xingmu-secret-key
    expire: 3600