server:
    port: 8080

spring:
    application:
        name: xingmu-user-service
    datasource:
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
      url: jdbc:shardingsphere:classpath:shardingsphere-user.yaml