server:
  port: 7999

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: xingmu-pay-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-pay.yaml
    uid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/xingmu_config?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 223375
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
feign:
  sentinel:
    enabled: true
alipay:
  alipay-public-key:
  app-id:
  content-key:
  gateway-url:
  merchant-private-key:
  notify-url:
  return-url:
  seller-id: